### ISSUE TITLE
Cannot bind address 

### ISSUE THREAD

**Issue by golden777** [TLINDEN/udpxd#9]
/udpxd# udpxd -l 0.0.0.0:54 -b 1.1.1.1 -t 1.1.1.1:53
Cannot bind address ([1.1.1.1]:0)
Cannot assign requested address
Cannot bind address ([1.1.1.1]:0)
Cannot assign requested address
Cannot bind address ([1.1.1.1]:0)
Cannot assign requested address

**Comment by TLINDEN** [comment]
Please show the output of `ifconfig -a` and run the command with `strace`. Thx.
